services:
  app:
    image: ${IMAGE}
    pull_policy: "missing"
    init: true
    volumes:
      - type: bind
        source: "./"
        target: "/root/work"
        consistency: "consistent"
      - type: bind
        source: ${GIT_CONFIG}
        target: "/root/.gitconfig"
      - type: bind
        source: ${SSH_DIR}
        target: "/root/.ssh"
    entrypoint: /root/show-help-in-app-container-then-wait.sh
    working_dir: /root/work

