services:
  app:
    image: ${IMAGE}
    pull_policy: "missing"
    init: true
    volumes:
      - type: bind
        source: ${PWD}
        target: ${PWD}
        consistency: "consistent"
      - type: bind
        source: ${GIT_CONFIG}
        target: "/root/.gitconfig"
    entrypoint: /root/show-help-in-app-container-then-wait.sh
    working_dir: ${PWD}
    ports:
      - "8086:8086"

