services:
  app:
    image: ${IMAGE}
    pull_policy: "missing"
    init: true
    volumes:
      - type: bind
        source: ${PWD}
        target: ${PWD}
        consistency: "consistent"
      # This allows access to Git configuration so Git commands work
      - type: bind
        source: ${GIT_CONFIG}
        target: "/home/appuser/.gitconfig"
      - type: bind
        source: "/var/run/docker.sock"
        target: "/var/run/docker.sock"
    command: /home/appuser/show-help-in-app-container-then-wait.sh
    working_dir: ${PWD}
    environment:
      PROJECT_ROOT: ${PWD}
    ports:
      - "8086:8086"
      - "8087:8087"

