#!/bin/bash

set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${0}" )" > /dev/null 2>&1 && pwd )

. "${SCRIPT_DIR}/dx.sh.lib"

require_command "docker"
load_docker_compose_env

usage_on_help "Builds the Docker image based on the Dockerfile" "" "build.pre" "build.post" "${@}"

if ! exec_hook_if_exists "build.pre" Dockerfile.dx "${IMAGE}"; then
  log "build.pre failed"
  exit 1
fi
build_args_file="${SCRIPT_DIR}/build.args"
BUILD_ARGS=()
if [ -e "${build_args_file}" ]; then
  for arg in `grep -v '^#' "${build_args_file}"`; do
    BUILD_ARGS+=(--build-arg ${arg})
  done
fi

docker build \
  --file Dockerfile.dx \
  --progress plain \
  --tag "${IMAGE}" ${BUILD_ARGS[@]} \
  ./

exec_hook_if_exists "build.post" Dockerfile.dx "${IMAGE}"

log "🌈" "Your Docker image has been built tagged '${IMAGE}'"
log "🔄" "You can now run dx/start to start it up, though you may need to stop it first with Ctrl-C"

# vim: ft=bash
