class MKBrut::Segments::Heroku < MKBrut::Base
  def self.friendly_name = "Heroku-based Deployment"

  def initialize(app_options:, current_dir:, templates_dir:)
    @project_root  = current_dir / app_options.app_name
    @templates_dir = templates_dir / "segments" / "Heroku"
    @erb_binding   = MKBrut::ErbBindingDelegate.new(app_options)
  end

  def add!
    operations = copy_files(@templates_dir, @project_root) + 
                 other_operations

    operations.each do |operation|
      operation.call
    end
  end

  def other_operations
    [
      MKBrut::Ops::AppendToFile.new(
        file: @project_root / ".gitignore",
        content: %{
# These are generated by bin/deploy
deploy/Dockerfile.*
}
      )
    ]
  end
end
